# Generated by Django 4.1.7 on 2023-03-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='slot',
            field=models.CharField(choices=[('A', '2 PM'), ('B', '2:30 PM'), ('C', '3 PM'), ('D', '3:30 PM'), ('E', '4 PM'), ('F', '4:30 PM')], default='2 PM', max_length=10),
        ),
    ]
