# Generated by Django 4.1.7 on 2023-03-12 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='day',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='time',
            new_name='slot',
        ),
    ]
