# Generated by Django 4.1.7 on 2023-03-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_appointment_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='slot',
            field=models.CharField(blank=True, choices=[('10 am', '10 am'), ('11 am', '11 am'), ('12 am', '12 am'), ('14 am', '14 am'), ('15 am', '15 am'), ('16 am', '16 am')], max_length=10, null=True),
        ),
    ]
