# Generated by Django 4.1.7 on 2023-03-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_appointment_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='slot',
            field=models.CharField(blank=True, choices=[('10 am', '10 am'), ('11 am', '11 am'), ('12 pm', '12 pm'), ('14 pm', '14 pm'), ('15 pm', '15 pm'), ('16 pm', '16 pm')], max_length=10, null=True),
        ),
    ]
