# Generated by Django 4.1.7 on 2023-03-19 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
        ('booking', '0008_alter_appointment_slot'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('student', 'booked')},
        ),
    ]
